# Pyright cannot statically evaluate this package's intentionally comprehensive
# export list, but Python and packaging smoke tests validate it directly.
# pyright: reportUnsupportedDunderAll=false

from .context import (
    AccountContext,
    DataContext,
    IndicatorContext,
    LoggingContext,
    OrderContext,
    ParamsContext,
    PositionContext,
    StorageContext,
    StrategyContext,
    TimeContext,
    IndicatorUpdateMode,
    MAX_BAR_LIMIT,
    MAX_TICK_LIMIT,
    DEFAULT_TICK_LIMIT,
    DEFAULT_BAR_LIMIT,
    MAX_INDICATOR_HISTORY_SIZE,
    MIN_INDICATOR_HISTORY_SIZE,
    DEFAULT_INDICATOR_HISTORY_SIZE,
)

from .models import (
    Bar,
    Quote,
    Tick,
    FinancialFactor,
    Order,
    OrderIntent,
    OrderStatus,
    OrderSide,
    OrderType,
    TimeInForce,
    Account,
    Position,
    SessionType,
    MarketStatus,
    MarketSession,
    Currency,
    Money,
    Fill,
    MarketEventType,
    TradingHaltScope,
    MarketEvent,
    PreMarketOpenEvent,
    MarketOpenEvent,
    MarketCloseEvent,
    PostMarketCloseEvent,
    TradingHaltedEvent,
    TradingResumedEvent,
    SplitEvent,
    DividendEvent,
    SymbolChangeEvent,
    DelistingWarningEvent,
    DelistingEvent
)

from .indicators import (
    Indicator,
    Accelerator,
    AD,
    ADX,
    ADXW,
    ASI,
    ATR,
    AwesomeOscillator,
    BB,
    Bears,
    Bulls,
    BWZoneTrade,
    CCI,
    CHO,
    CHV,
    DEMA,
    DeMarker,
    DPO,
    EMA,
    Envelopes,
    ForceIndex,
    Fractals,
    FrAMA,
    Gator,
    HeikenAshi,
    MACD,
    SMA,
)

from .errors import (
    SDKError,
    DataErrorCode,
    DataResource,
    DataError,
    DataNotFoundError,
    DataUnavailableError,
    DataStaleError,
    DataAccessError,
    DataRateLimitedError,
    DataTimeoutError,
    DataIncompleteError,
    DataInvalidRangeError,
    DataUnsupportedTimeframeError,
    OrderErrorCode,
    OrderError,
    OrderInvalidQuantityError,
    OrderInvalidPriceError,
    OrderInvalidStopPriceError,
    OrderInvalidTrailValueError,
    OrderUnsupportedConfigurationError,
    OrderRejectedError,
    OrderOperationFailedError,
    ValidationErrorCode,
    ValidationError,
    MissingParameterError,
    InvalidTypeError,
    InvalidValueError,
    OutOfRangeError,
    InvalidStateError,
    SchemaViolationError,
    IncompleteInputError,
    ConstraintViolationError,
    IncompatibleParametersError,
    InvalidFormatError,
    UnsupportedValueError,
    DuplicateValueError,
    InvalidPrecisionError,
)

from .strategy import Strategy

from .typedefs import (
    Symbol,
    InstrumentId,
    Timeframe,
    Timestamp,
    TimestampLike,
    DateLike,
    QuantityValue,
    PriceValue,
    CashValue,
    PercentValue,
    OrderId
)

from .utils import (
    to_datetime,
    to_date,
    now_utc,
    today_utc,
    timeframe_to_timedelta,
    safe_div,
    is_close,
    clamp,
    normalize,
    to_percent,
    from_percent,
    round_to,
    is_finite,
    require_not_none,
    require_type,
    require_positive,
    require_range,
    require_non_empty,
    require_in,
    require_enum,
    normalize_symbol,
)

__all__ = [
    # Strategy
    "Strategy",

    # Contexts
    "AccountContext",
    "DataContext",
    "IndicatorContext",
    "LoggingContext",
    "OrderContext",
    "ParamsContext",
    "PositionContext",
    "StorageContext",
    "StrategyContext",
    "TimeContext",
    "IndicatorUpdateMode",
    "MAX_BAR_LIMIT",
    "MAX_TICK_LIMIT",
    "DEFAULT_TICK_LIMIT",
    "DEFAULT_BAR_LIMIT",
    "MAX_INDICATOR_HISTORY_SIZE",
    "MIN_INDICATOR_HISTORY_SIZE",
    "DEFAULT_INDICATOR_HISTORY_SIZE",    

    # Market data models
    "Bar",
    "Quote",
    "Tick",
    "FinancialFactor",

    # Order models and enums
    "Order",
    "OrderIntent",
    "OrderStatus",
    "OrderSide",
    "OrderType",
    "TimeInForce",
    "Fill",

    # Account and portfolio models
    "Account",
    "Position",
    "Currency",
    "Money",

    # Market session models and enums
    "SessionType",
    "MarketStatus",
    "MarketSession",
    "MarketEventType",
    "TradingHaltScope",
    "MarketEvent",
    "PreMarketOpenEvent",
    "MarketOpenEvent",
    "MarketCloseEvent",
    "PostMarketCloseEvent",
    "TradingHaltedEvent",
    "TradingResumedEvent",
    "SplitEvent",
    "DividendEvent",
    "SymbolChangeEvent",
    "DelistingWarningEvent",
    "DelistingEvent",

    # Indicators    
    "Indicator",
    "Accelerator",
    "AD",
    "ADX",
    "ADXW",
    "ASI",
    "ATR",
    "AwesomeOscillator",
    "BB",
    "Bears",
    "Bulls",
    "BWZoneTrade",
    "CCI",
    "CHO",
    "CHV",
    "DEMA",
    "DeMarker",
    "DPO",
    "EMA",
    "Envelopes",
    "ForceIndex",
    "Fractals",
    "FrAMA",
    "Gator",
    "HeikenAshi",
    "MACD",
    "SMA",

    # Base SDK errors
    "SDKError",

    # Data errors
    "DataErrorCode",
    "DataResource",
    "DataError",
    "DataNotFoundError",
    "DataUnavailableError",
    "DataStaleError",
    "DataAccessError",
    "DataRateLimitedError",
    "DataTimeoutError",
    "DataIncompleteError",
    "DataInvalidRangeError",
    "DataUnsupportedTimeframeError",

    # Order errors
    "OrderErrorCode",
    "OrderError",
    "OrderInvalidQuantityError",
    "OrderInvalidPriceError",
    "OrderInvalidStopPriceError",
    "OrderInvalidTrailValueError",
    "OrderUnsupportedConfigurationError",
    "OrderRejectedError",
    "OrderOperationFailedError",

    # Validation errors
    "ValidationErrorCode",
    "ValidationError",
    "MissingParameterError",
    "InvalidTypeError",
    "InvalidValueError",
    "OutOfRangeError",
    "InvalidStateError",
    "SchemaViolationError",
    "IncompleteInputError",
    "ConstraintViolationError",
    "IncompatibleParametersError",
    "InvalidFormatError",
    "UnsupportedValueError",
    "DuplicateValueError",
    "InvalidPrecisionError",

    # Type aliases
    "Symbol",
    "InstrumentId",
    "Timeframe",
    "Timestamp",
    "TimestampLike",
    "DateLike",
    "QuantityValue",
    "PriceValue",
    "CashValue",
    "PercentValue",
    "OrderId",

    # Date and time utilities
    "to_datetime",
    "to_date",
    "now_utc",
    "today_utc",
    "timeframe_to_timedelta",

    # Numeric utilities
    "safe_div",
    "is_close",
    "clamp",
    "normalize",
    "to_percent",
    "from_percent",
    "round_to",
    "is_finite",

    # Validation utilities
    "require_not_none",
    "require_type",
    "require_positive",
    "require_range",
    "require_non_empty",
    "require_in",
    "require_enum",

    # Symbol utilities
    "normalize_symbol",
]
