from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from enum import StrEnum

from ..typedefs import CashValue, Symbol, Timestamp
from .common import Currency


class MarketEventType(StrEnum):
    """
    Define market-related event types generated by the platform.

    Market events are delivered to strategies through
    ``Strategy.on_event()``.

    Members
    -------
    PRE_MARKET_OPEN
        Indicates that the pre-market trading session has opened.
    MARKET_OPEN
        Indicates that the regular trading session has opened.
    MARKET_CLOSE
        Indicates that the regular trading session has closed.
    POST_MARKET_CLOSE
        Indicates that the post-market trading session has closed.
    TRADING_HALTED
        Indicates that trading has been temporarily halted.
    TRADING_RESUMED
        Indicates that trading has resumed after a halt.
    SPLIT
        Indicates a stock split or reverse stock split.
    DIVIDEND
        Indicates a cash-dividend distribution.
    SYMBOL_CHANGE
        Indicates that a security's trading symbol has changed.
    DELISTING_WARNING
        Indicates that a security is scheduled for delisting.
    DELISTING
        Indicates that a security has been delisted.
    """

    PRE_MARKET_OPEN = "pre_market_open"
    MARKET_OPEN = "market_open"
    MARKET_CLOSE = "market_close"
    POST_MARKET_CLOSE = "post_market_close"

    TRADING_HALTED = "trading_halted"
    TRADING_RESUMED = "trading_resumed"

    SPLIT = "split"
    DIVIDEND = "dividend"
    SYMBOL_CHANGE = "symbol_change"
    DELISTING_WARNING = "delisting_warning"
    DELISTING = "delisting"


class TradingHaltScope(StrEnum):
    """
    Define the scope affected by a trading halt or resumption.

    Members
    -------
    SYMBOL
        The event applies to one security.
    MARKET
        The event applies to an entire market.
    VENUE
        The event applies to an exchange or trading venue.
    """

    SYMBOL = "symbol"
    MARKET = "market"
    VENUE = "venue"


@dataclass(frozen=True, slots=True, kw_only=True)
class MarketEvent:
    """
    Represent a market event delivered to a strategy.

    Attributes
    ----------
    type
        Type of market event.
    occurred_at
        Time when the market event occurred.
    """

    type: MarketEventType
    occurred_at: Timestamp


@dataclass(frozen=True, slots=True, kw_only=True)
class PreMarketOpenEvent(MarketEvent):
    """
    Represent the opening of the pre-market trading session.
    """

    type: MarketEventType = field(
        default=MarketEventType.PRE_MARKET_OPEN,
        init=False,
    )


@dataclass(frozen=True, slots=True, kw_only=True)
class MarketOpenEvent(MarketEvent):
    """
    Represent the opening of the regular trading session.
    """

    type: MarketEventType = field(
        default=MarketEventType.MARKET_OPEN,
        init=False,
    )


@dataclass(frozen=True, slots=True, kw_only=True)
class MarketCloseEvent(MarketEvent):
    """
    Represent the closing of the regular trading session.
    """

    type: MarketEventType = field(
        default=MarketEventType.MARKET_CLOSE,
        init=False,
    )


@dataclass(frozen=True, slots=True, kw_only=True)
class PostMarketCloseEvent(MarketEvent):
    """
    Represent the closing of the post-market trading session.
    """

    type: MarketEventType = field(
        default=MarketEventType.POST_MARKET_CLOSE,
        init=False,
    )


@dataclass(frozen=True, slots=True, kw_only=True)
class TradingHaltedEvent(MarketEvent):
    """
    Represent a temporary trading halt.

    Attributes
    ----------
    scope
        Scope affected by the trading halt.
    symbol
        Security affected by a symbol-level halt.

        This field is required when ``scope`` is
        ``TradingHaltScope.SYMBOL``.
    market
        Market affected by a market-wide halt.

        This field is required when ``scope`` is
        ``TradingHaltScope.MARKET``.
    venue
        Exchange or trading venue affected by a venue-wide halt.

        This field is required when ``scope`` is
        ``TradingHaltScope.VENUE``.
    reason
        Platform- or exchange-provided explanation for the halt.
    halt_code
        Platform- or exchange-provided halt reason code.
    expected_resume_at
        Expected trading-resumption time.

        ``None`` indicates that no expected resumption time is available.
    """

    type: MarketEventType = field(
        default=MarketEventType.TRADING_HALTED,
        init=False,
    )

    scope: TradingHaltScope
    symbol: Symbol | None = None
    market: str | None = None
    venue: str | None = None
    reason: str | None = None
    halt_code: str | None = None
    expected_resume_at: Timestamp | None = None

    def __post_init__(self) -> None:
        """
        Validate that the event identifies its affected scope.
        """
        if self.scope is TradingHaltScope.SYMBOL and self.symbol is None:
            raise ValueError(
                "symbol is required when scope is TradingHaltScope.SYMBOL"
            )

        if self.scope is TradingHaltScope.MARKET and self.market is None:
            raise ValueError(
                "market is required when scope is TradingHaltScope.MARKET"
            )

        if self.scope is TradingHaltScope.VENUE and self.venue is None:
            raise ValueError(
                "venue is required when scope is TradingHaltScope.VENUE"
            )


@dataclass(frozen=True, slots=True, kw_only=True)
class TradingResumedEvent(MarketEvent):
    """
    Represent the resumption of trading after a halt.

    Attributes
    ----------
    scope
        Scope for which trading resumed.
    symbol
        Security for which trading resumed.

        This field is required when ``scope`` is
        ``TradingHaltScope.SYMBOL``.
    market
        Market for which trading resumed.

        This field is required when ``scope`` is
        ``TradingHaltScope.MARKET``.
    venue
        Exchange or trading venue for which trading resumed.

        This field is required when ``scope`` is
        ``TradingHaltScope.VENUE``.
    halt_code
        Halt code associated with the original trading halt.
    """

    type: MarketEventType = field(
        default=MarketEventType.TRADING_RESUMED,
        init=False,
    )

    scope: TradingHaltScope
    symbol: Symbol | None = None
    market: str | None = None
    venue: str | None = None
    halt_code: str | None = None

    def __post_init__(self) -> None:
        """
        Validate that the event identifies its affected scope.
        """
        if self.scope is TradingHaltScope.SYMBOL and self.symbol is None:
            raise ValueError(
                "symbol is required when scope is TradingHaltScope.SYMBOL"
            )

        if self.scope is TradingHaltScope.MARKET and self.market is None:
            raise ValueError(
                "market is required when scope is TradingHaltScope.MARKET"
            )

        if self.scope is TradingHaltScope.VENUE and self.venue is None:
            raise ValueError(
                "venue is required when scope is TradingHaltScope.VENUE"
            )


@dataclass(frozen=True, slots=True, kw_only=True)
class SplitEvent(MarketEvent):
    """
    Represent a stock split or reverse stock split.

    The runtime applies the split to positions, eligible open orders,
    account state, and affected indicator state before delivering the
    event to the strategy.

    Attributes
    ----------
    symbol
        Security affected by the split.
    new_shares
        Number of new shares in the split ratio.
    old_shares
        Number of old shares in the split ratio.
    effective_at
        Time when the split becomes effective.

    Examples
    --------
    A 2-for-1 split uses ``new_shares=2.0`` and ``old_shares=1.0``.

    A 1-for-10 reverse split uses ``new_shares=1.0`` and
    ``old_shares=10.0``.
    """

    type: MarketEventType = field(
        default=MarketEventType.SPLIT,
        init=False,
    )

    symbol: Symbol
    new_shares: float
    old_shares: float
    effective_at: Timestamp

    @property
    def quantity_factor(self) -> float:
        """
        Return the position-quantity adjustment factor.

        Returns
        -------
        float
            Number of new shares received for each old share.
        """
        return self.new_shares / self.old_shares

    @property
    def price_factor(self) -> float:
        """
        Return the corresponding price-adjustment factor.

        Returns
        -------
        float
            Factor applied to pre-split prices.
        """
        return self.old_shares / self.new_shares


@dataclass(frozen=True, slots=True, kw_only=True)
class DividendEvent(MarketEvent):
    """
    Represent a cash-dividend distribution.

    The runtime updates the account cash balance before delivering the
    event when the dividend payment becomes effective.

    Attributes
    ----------
    symbol
        Security paying the dividend.
    amount_per_share
        Dividend amount paid for each eligible share.
    currency
        Currency of the dividend payment.
    ex_date
        First trading date on which buyers do not receive the dividend.
    record_date
        Date on which eligible shareholders are recorded.
    payment_date
        Date on which the dividend is paid.
    """

    type: MarketEventType = field(
        default=MarketEventType.DIVIDEND,
        init=False,
    )

    symbol: Symbol
    amount_per_share: CashValue
    currency: Currency
    ex_date: date
    record_date: date | None = None
    payment_date: date | None = None


@dataclass(frozen=True, slots=True, kw_only=True)
class SymbolChangeEvent(MarketEvent):
    """
    Represent a change to a security's trading symbol.

    The instrument identity remains unchanged. The event records the old
    and new symbols used to reference the instrument.

    Attributes
    ----------
    old_symbol
        Trading symbol used before the change.
    new_symbol
        Trading symbol used after the change.
    effective_at
        Time when the new symbol becomes effective.
    """

    type: MarketEventType = field(
        default=MarketEventType.SYMBOL_CHANGE,
        init=False,
    )

    old_symbol: Symbol
    new_symbol: Symbol
    effective_at: Timestamp


@dataclass(frozen=True, slots=True, kw_only=True)
class DelistingWarningEvent(MarketEvent):
    """
    Represent an upcoming security delisting.

    The warning gives the strategy an opportunity to cancel orders or
    close an open position before the final delisting.

    Attributes
    ----------
    symbol
        Security scheduled for delisting.
    delisting_at
        Scheduled delisting time.
    reason
        Explanation for the delisting.
    """

    type: MarketEventType = field(
        default=MarketEventType.DELISTING_WARNING,
        init=False,
    )

    symbol: Symbol
    delisting_at: Timestamp
    reason: str | None = None


@dataclass(frozen=True, slots=True, kw_only=True)
class DelistingEvent(MarketEvent):
    """
    Represent the final delisting of a security.

    The runtime cancels eligible open orders, applies the configured
    position-handling policy, and synchronizes SDK-visible state before
    delivering the event.

    Attributes
    ----------
    symbol
        Delisted security.
    effective_at
        Time when the delisting became effective.
    reason
        Explanation for the delisting.
    """

    type: MarketEventType = field(
        default=MarketEventType.DELISTING,
        init=False,
    )

    symbol: Symbol
    effective_at: Timestamp
    reason: str | None = None